# Poblar la base de datos

In [1067]:
from random import randint, seed, random
seed(123456789)

In [1068]:
import mysql.connector as connection

#### Funciones auxiliares

In [1069]:
def query(q, many: bool, *args):
    try:
        mydb = connection.connect(host="localhost", database = 'practica',user="root", passwd="root", use_pure=True)
        cursor = mydb.cursor(buffered=True)
        if many:
            cursor.executemany(q, *args)
        else:
            res = cursor.execute(q, *args)
        mydb.commit()
    except Exception as e:
        res = 'Excepcion ' + str(e)
    finally:
        # cursor.close()
        mydb.close()
    return res

In [1070]:
def insert(table, campos, data, many: bool = False):
    if not len(campos) or not len(data):
        return 'Empty row'

    q = f'insert into {table} ({", ".join(campos)}) values ({", ".join(["%s"] * len(data[0] if many else data))})'
    res = None
    try:
        mydb = connection.connect(host="localhost", database = 'practica',user="root", passwd="root", use_pure=True)
        cursor = mydb.cursor(buffered=True)
        if many:
            res = cursor.executemany(q, data)
        else:
            res = cursor.execute(q, data)
        mydb.commit()
    except Exception as e:
        res = 'Excepcion ' + str(e)
    finally:
        # cursor.close()
        mydb.close()
    return res

#### Reinicio de los datos en la base de datos

In [1071]:
query('delete from pr_empleados_proyecto', False)

In [1072]:
query('delete from em_empleados', False)

In [1073]:
query('delete from pr_proyectos', False)

### Empleados

#### Nombres

In [1074]:
nombres = [
'Alfred',
'Leila',
'Bertie',
'Barry',
'Emma',
'Johanna',
'Willie',
'Maria',
'Josephine',
'Lura',
'Adrian',
'Cory',
'Michael',
'Mary',
'Beulah',
'Kyle',
'Leah',
'Ina',
'Owen',
'Jorge',
'Troy',
'Christine',
'Dylan',
'Chris',
'Chris',
'Clara',
'Verna',
'Amanda',
'Clayton',
'Micheal',
'Jeffrey',
'Stella',
'Katie',
'Trevor',
'Phoebe',
'Allen',
'Maud',
'Margaret',
'Harvey',
'Nettie',
'Isabelle',
'Alma',
'Esther',
'Jean',
'Roy',
'Julian',
'Devin',
'Douglas',
'Julian',
'Ivan',
'Patrick',
'Angel',
'Sue',
'Steve',
'Jimmy',
'Etta',
'Rebecca',
'Francisco',
'Clayton',
'David',
'Marguerite',
'Hattie',
'Vera',
'Mollie',
'Effie',
'Amanda',
'Glenn',
'Eula',
'Lenora',
'Bruce',
'Isabelle',
'Gilbert',
'Cecilia',
'Leona',
'Rebecca',
'Jim',
'Bryan',
'Leah',
'Emma',
'Rosa',
'Isaac',
'Daisy',
'Evan',
'Joshua',
'Dylan',
'Ruby',
'Franklin',
'Theodore',
'Adele',
'Evelyn',
'Katie',
'Roger',
'Catherine',
'Bertie',
'Betty',
'Jonathan',
'Elva',
'Isabella',
'Dominic',
'Roxie',
]

#### Apellidos

In [1075]:
apellidos = [
    ('White', 'Phillips'),
('Hamilton', 'Welch'),
('Fletcher', 'Wilson'),
('Adkins', 'Butler'),
('Morgan', 'Bates'),
('Soto', 'Gonzales'),
('Doyle', 'Lawrence'),
('Burton', 'Rios'),
('Ramsey', 'Bowman'),
('Webb', 'McBride'),
('Clark', 'Cooper'),
('Leonard', 'Simon'),
('Rogers', 'Hall'),
('McCarthy', 'Stevens'),
('Bailey', 'Montgomery'),
('Chandler', 'Logan'),
('Pena', 'Pierce'),
('Farmer', 'Guerrero'),
('Valdez', 'White'),
('Pierce', 'Conner'),
('Hawkins', 'Hawkins'),
('Lloyd', 'Morales'),
('Miles', 'Alvarez'),
('Austin', 'Phillips'),
('Keller', 'Hall'),
('Santos', 'Davidson'),
('Wallace', 'Clayton'),
('Ross', 'Griffin'),
('Dean', 'Robbins'),
('Ruiz', 'Mendoza'),
('Soto', 'Perry'),
('Cohen', 'White'),
('Garcia', 'Ortiz'),
('Jennings', 'Vaughn'),
('Beck', 'Lindsey'),
('Parker', 'Larson'),
('Lamb', 'Goodman'),
('Sanders', 'Barnes'),
('Nichols', 'Thornton'),
('Silva', 'Morgan'),
('Lloyd', 'Jones'),
('Alexander', 'Collins'),
('Wilkerson', 'Todd'),
('Boyd', 'Sparks'),
('Guzman', 'Franklin'),
('Singleton', 'Watson'),
('Bailey', 'Hunt'),
('Reed', 'Pope'),
('Willis', 'Adkins'),
('Hughes', 'Zimmerman'),
('Banks', 'Oliver'),
('Herrera', 'Jenkins'),
('Spencer', 'Crawford'),
('Richards', 'Gonzalez'),
('Wong', 'Schneider'),
('Ramirez', 'Boyd'),
('Stone', 'Rice'),
('Fuller', 'Francis'),
('Brock', 'Reed'),
('Jensen', 'Park'),
('George', 'Morgan'),
('Hopkins', 'McBride'),
('Nelson', 'George'),
('Jackson', 'Malone'),
('Padilla', 'Caldwell'),
('Hardy', 'Scott'),
('Copeland', 'Santos'),
('Wilkerson', 'Lowe'),
('Castro', 'Ford'),
('Gilbert', 'Moody'),
('Allen', 'Cruz'),
('Gutierrez', 'Anderson'),
('Boyd', 'Wells'),
('Gonzales', 'Simon'),
('Ruiz', 'Fernandez'),
('Lawson', 'Ruiz'),
('Knight', 'Neal'),
('Brock', 'Williamson'),
('Mack', 'Porter'),
('Mathis', 'Rhodes'),
('Garner', 'Moran'),
('Bell', 'Lee'),
('Romero', 'Pierce'),
('Perkins', 'Howell'),
('Benson', 'Luna'),
('Gonzalez', 'Moreno'),
('Daniel', 'Townsend'),
('Parker', 'Reynolds'),
('Jefferson', 'Thompson'),
('Carter', 'Chambers'),
('Lawrence', 'Brewer'),
('Fuller', 'Martin'),
('Obrien', 'Russell'),
('Long', 'Daniel'),
('Patrick', 'Mills'),
('Higgins', 'Burgess'),
('Holt', 'Logan'),
('Gutierrez', 'Pearson'),
('Hernandez', 'Wade'),
('McGee', 'Walker'),

]

#### Nifs

In [1076]:
nifs = [
    '88953399G',
'42401933C',
'52971090P',
'41056311G',
'70090020R',
'39581105Y',
'28488227G',
'43086195O',
'71097792Z',
'50940281T',
'86501636G',
'67412007O',
'26903374Y',
'66005749T',
'40777634B',
'98148915Y',
'90151977P',
'27423078R',
'11098911Y',
'27194980B',
'37621966W',
'60418820C',
'59244296E',
'76713311T',
'50976007N',
'48825826D',
'32243889T',
'36447179L',
'73670062L',
'39489420X',
'47986253B',
'81369158S',
'11004592E',
'39366423K',
'35746034W',
'95326377K',
'92864188D',
'48822127X',
'13701029X',
'97607064G',
'13761491E',
'47447522D',
'70866763E',
'44279930F',
'28370947P',
'35106139V',
'87541974K',
'70903799V',
'94343208E',
'36835190O',
'28116799D',
'96128200B',
'76438292A',
'98318129J',
'79260073L',
'25070679J',
'71210354Y',
'74656829E',
'60061445S',
'34065433J',
'75772108D',
'26754843V',
'51692259D',
'36700275Z',
'76690525T',
'45848829G',
'47299129S',
'44704219U',
'46842034K',
'71007634Z',
'83007275T',
'16638807K',
'65770597D',
'21753788C',
'56683647H',
'44924233H',
'30559162S',
'21225536A',
'45078725L',
'82685909O',
'76859765D',
'94714323F',
'68774424K',
'30644966W',
'26117201R',
'47678685M',
'18178099P',
'38245621S',
'16216380C',
'14136084Y',
'43167059Z',
'64893233H',
'51652556X',
'70040501X',
'25863860F',
'14153748T',
'93603475R',
'83677683X',
'14920129H',
'82280834H',
]

#### Fnacimiento

In [1077]:
fnacimiento = [
    (1986, 2, 18),
(1993, 3, 25),
(1978, 10, 23),
(1991, 10, 17),
(1979, 6, 16),
(1994, 10, 11),
(1971, 12, 9),
(1980, 7, 28),
(1984, 7, 22),
(1998, 12, 5),
(1981, 5, 10),
(1989, 1, 17),
(1990, 1, 14),
(1988, 8, 13),
(1994, 12, 2),
(1999, 12, 1),
(1994, 1, 22),
(1984, 5, 22),
(1978, 1, 6),
(1976, 2, 13),
(1974, 3, 12),
(1979, 7, 13),
(1980, 4, 6),
(1987, 6, 9),
(1976, 12, 20),
(2003, 8, 11),
(1998, 7, 18),
(1973, 12, 10),
(1974, 6, 1),
(1984, 12, 23),
(1983, 6, 8),
(1990, 10, 23),
(1976, 10, 1),
(1978, 8, 2),
(1975, 12, 27),
(1975, 3, 22),
(1979, 3, 1),
(1996, 10, 15),
(2000, 6, 9),
(1978, 3, 27),
(1996, 12, 16),
(1988, 6, 3),
(1986, 1, 1),
(1986, 5, 17),
(1990, 2, 3),
(1998, 4, 12),
(1999, 10, 7),
(2000, 8, 8),
(1977, 4, 20),
(1988, 8, 27),
(1984, 4, 15),
(1977, 8, 27),
(1980, 11, 20),
(1993, 10, 2),
(1999, 5, 17),
(1987, 11, 3),
(1985, 8, 27),
(1981, 5, 24),
(1998, 6, 1),
(1999, 9, 6),
(1984, 7, 26),
(1975, 3, 14),
(1996, 5, 12),
(1991, 4, 1),
(1983, 7, 4),
(1997, 1, 3),
(1998, 2, 2),
(1973, 2, 1),
(1986, 1, 12),
(1976, 10, 19),
(1997, 1, 21),
(1996, 4, 24),
(1970, 12, 13),
(1993, 11, 15),
(1991, 12, 4),
(1990, 11, 2),
(1973, 6, 1),
(1992, 6, 28),
(1984, 11, 24),
(2003, 2, 2),
(1977, 7, 11),
(1975, 8, 14),
(1998, 2, 19),
(1973, 8, 17),
(1975, 6, 4),
(1970, 4, 10),
(1972, 7, 3),
(1992, 6, 4),
(1982, 9, 7),
(2000, 9, 7),
(2001, 8, 8),
(1975, 9, 26),
(1994, 1, 4),
(1983, 2, 12),
(1987, 8, 22),
(1972, 2, 15),
(1977, 3, 23),
(1999, 7, 10),
(1976, 9, 10),
(1990, 10, 23),

]

#### Falta

In [1078]:
offset = 5
falta = [
    (min(2021, y + 17 + randint(1, 10), randint(y + 18 + offset, 2022 + offset) - randint(offset, 2022 - y + 18)), randint(1, 12), randint(1, 28))
    for y, _, _ in fnacimiento
]

#### Fbaja

In [1079]:
propPresente = 0.7
fbaja = [
    None if random() < propPresente else (randint(y + 1, 2023), randint(1, 12), randint(1, 28))
    for y, _, _ in falta
]

#### Agrupacion

In [1080]:
tabla_e = 'em_empleados'
campos_e = ('ID_EMPLEADO', 'tx_Nif', 'tx_Nombre', 'tx_Apellido1', 'tx_Apellido2', 'f_Nacimiento', 'n_Telefono1', 'n_Telefono2', 'tx_Email', 'f_Alta', 'f_Baja', 'cx_Edocivil', 'b_Servmilitar')
pSoltero = 0.6
pMilitar = 0.15

fdate = lambda f: None if f is None else f'{str(f[0]).zfill(4)}-{str(f[1]).zfill(2)}-{str(f[2]).zfill(2)}'

data_e = [
    (
        i+1, nifs[i%len(nifs)], nombres[i%len(nombres)], apellidos[i%len(apellidos)][0], apellidos[i%len(apellidos)][1],
        fdate(fnacimiento[i%len(fnacimiento)]),
        randint(100000000, 999999999), randint(100000000, 999999999), f'{nombres[i%len(nombres)].lower()}.{apellidos[i%len(apellidos)][0].lower()}@gmail.com',
        fdate(falta[i]), fdate(fbaja[i]), ('S' if random() < pSoltero else 'C'), ('S' if random() < pMilitar else 'N')
    )
    for i in range(len(nifs))
]

#### Insercion

In [1081]:

insert(tabla_e, campos_e, data_e, True)

### Proyectos

#### Datos

In [1082]:
descripciones = [
'Gone club temperature provide excellent nearer',
'Acres research fun track somehow',
'Tent bent temperature itself identity grandfather could steep',
'Extra vertical vowel count',
'Train inch raise are',
'Means state',
'Star garden jar duty ten grain',
'Imagine cage',
'Star equipment locate box no',
'Knife nodded make terrible wait',
'Cause member scale receive trail',
'Sold pencil ahead without third',
'Screen monkey herd',
'Held unhappy spin pull cause',
'Animal cross wish forest give deal',
'Push increase clothing jack straw',
'Quick oldest lesson',
'Diameter too chest safety exchange',
'Swing whether grew classroom share member',
'Setting tell angle stand minute natural',
'Difference imagine wrapped tide low cup',
'Roll usually choice been further',
'Health graph from',
'Bare disappear special dust folks realize practical',
'For particles your',
'Loose crop empty anyway',
'Main surface quietly',
'Worried chief how agree storm diameter',
'Wall setting gave mathematics',
'Identity west zoo stiff paint',
'Temperature price south stream create',
'Agree first see quick impossible',
'Did properly jungle price pet',
'Origin tea fully does',
'Larger game size dull seems method',
'Meal shade within require',
'Whose became hill fine face activity',
'Getting deal lead garage bet',
'What correctly show straw cold',
'Game saw rocky driver ought today',
'Spider branch hat save origin',
'Harder reader effect saddle',
'Pattern level hollow branch matter moment',
'Course moment dig new gasoline business outer',
'Voyage spell slide yet few',
'Place anywhere temperature women line location',
'Program common bring who',
'Vertical important giving',
'Smoke',
'Huge tell mean eye medicine bag longer dig',
]

In [1083]:
lugares = [
'Madrid',
'Barcelona',
'Valencia',
'Sevilla',
'Zaragoza',
'Málaga',
]

In [1084]:
observaciones = [
    o.capitalize()
    for o in [
'gave send sad purple settle feet drawn sure ourselves solution rabbit doctor summer yes card expect tears dig fresh given round place primitive matter',
'little rubber fierce hearing baby one regular firm space nearly clay remove shot off basket stove rich entire police picture shaking oxygen religious month',
'universe answer lying pink price easier bread lips neighbor mixture fix too struggle let peace rough block gift paid distant silent wolf idea property',
'that directly hall cream nearly anyone plant behind root voice being satellites height cell some longer butter sail exciting solid chose port twelve obtain',
'invented properly weak cookies needed hung breathe tone television single exercise try key broken adult end hair learn fresh pan lips limited lost length',
'lack lips hour harbor regular cat familiar beyond pond positive habit daughter current discover fix shout handsome making series crack job specific shore out',
'well children tears usually caught noon paragraph park its golden order school whale football bank tube tone wealth these attention happened person behind start',
'dot remove unhappy tobacco religious parallel already black look children if powder so hurry count possibly also far beautiful war anything wild select partly',
'done cast welcome apart children lion prevent drive chamber skill ten period identity colony managed pass uncle shoot bus his rubber personal wood recognize',
'themselves answer today move wind local respect enjoy regular whenever anybody nine mile force everybody saw leaving am hardly cloth bent lost fight thought',
'individual upper harbor fifteen actually job lead prize we chair mirror situation being manufacturing suddenly smallest daughter my rod twice complex political pilot plan',
'age nuts club anybody generally beyond around needed giving longer night wish buffalo golden difficult describe policeman star regular signal round kind cookies whistle',
'engineer did problem living up equally molecular will official party several weak rabbit needed pool milk throw past material block given machinery wheel anyway',
'class friend education alike create gradually forgotten five talk come apple lying dozen recent breeze function solution right character stove limited ill town thee',
'since period getting youth making quickly vast globe lift pair though hang locate sand chart musical beneath successful boy nervous direction plural within jump',
'zero village power arrangement kitchen half describe women duck me box dug top deeply saddle lack frequently monkey location trick doubt chemical country tube',
'plus gather relationship behavior period cool calm white thin weather silk limited plant imagine cent brick combine of against importance citizen birth were sit',
'regular public unhappy independent led promised signal above shirt sit importance mass truck nation whole massage president machinery interior shoe cannot pleasant bell all',
'us accurate beautiful happy mad beat pain statement title thought couple ants nuts object could birth manufacturing price species previous brought dog shore girl',
'only hunt enjoy pleasant water area else to cutting angle already ride by branch write sit please hope stranger is wheat grabbed select paid',
'parallel whatever clay journey today floor clear wave suit simply correct guide breakfast smooth branch attempt selection gone sum progress current easier four wheel',
'sale hair treated hunter river while review none light equal mail found wrote stepped experience sets weak wolf walk clothing read wet saddle problem',
'swing everyone lift negative pack main single till pole summer paragraph slide package tightly passage cover leather sometime contrast represent rubbed private upper doll',
'smell chest end president courage two taught flame seat such castle musical sum similar merely shape while experience chapter why fill west buy tongue',
'amount place master pony mountain upward key bend development customs century slight needed trap first climb base bent fruit won discuss cookies highest between',
'circle secret fact child sometime read loose upper price angry day enough dot wonderful handsome thrown mind simple touch public father label fort salt',
'desk corner mistake joy railroad fierce constantly moment scientific yourself drop replace native other managed additional note political plus church floor ready piano do',
'throw stems face cow brave spoken forgotten flight square agree exact hold similar graph camera before clothing shoulder circle combination applied continued create flies',
'refused heavy shot correct eager area above copy pencil alive bite higher origin exist shall pitch longer pan handle book flat meet bottle distant',
'catch crowd light vote tiny clear condition figure quick table broad weight east lovely year perfectly damage fifth expect flat hour horn later circle',
'hundred mud shot state forgot that upon carry advice book physical exclaimed two atmosphere nails tears shop provide office loss combination dear about color',
'atomic indeed factory perhaps imagine number six potatoes aboard these rabbit double everywhere anything shown surface stand elephant nails available late various shade room',
'nor let stranger related soon husband silk tribe mass neighborhood cool cold examine firm horse return salt usually train military here dinner white welcome',
'environment clear shinning least mix through adventure began lion sent addition them continent wrong century including herself lost angry stone build kind progress nobody',
'sky shells ability word poet duck got eat held wing dress built region traffic crowd circle yesterday itself pink thread diameter lower blue rapidly',
'obtain slip thirty has built lady either also crack village studied owner clothes sentence twelve expression weight possibly planned house adjective stage nature thousand',
'bow dinner gravity bread believed position failed represent up pan done dirt refer safe outside tape globe largest does transportation plastic sent spin pass',
'education pine cook count block settle barn stuck iron spent fewer cow source garden arrive sum duck signal judge might week whether generally who',
'same read necessary attempt mark once distance story depend muscle pool colony earn pupil pure my got different railroad addition electricity recognize because thee',
'phrase name stopped rest spent myself also member built cause quietly short eaten interest enemy open room if pocket cow vote load becoming bowl',
'nose how solid red strike specific shoot firm since port have slept these play seven mind eleven bill given struggle lips hill end according',
'maybe band wear won sky biggest home serve track continued you bell color contrast quite coming ever accept base brave anywhere begun breath produce',
'railroad bean wood individual explore easier joined simplest does part figure new immediately courage attention opinion thee mean rod according brass do special little',
'three farmer wagon silver consonant mirror classroom rain old would chart contain evidence product nice call pie slightly tea tone broken native excellent judge',
'column equipment stomach world range mathematics pair prevent brother today hard turn tool toy straight trade cattle electric week interest pressure history court lady',
'talk bell corn mad along winter replace save send classroom suit list crowd rough wish jack blue load motor just usually front watch running',
'wonder gather none clay call forgot object giving somehow putting location anywhere slide sale paragraph deer failed palace exercise ground under wet reader wife',
'trunk eleven station numeral top source fierce garage seven anybody should mostly halfway teeth snow stomach son simple activity greatly harder butter substance star',
'massage including aid whistle reach contain orbit library soap atomic would fifteen softly price mysterious gain brave refused daughter smaller teacher opportunity stiff bar',
'shown identity rear member relationship rich tell structure salt protection under dry street negative suppose brother sheet gain rapidly because plus kind suggest compound',
]]

In [1085]:
pBaja = 0.3
minyalta = min(falta, key=lambda f: f[0])[0]
fini = [
    (randint(minyalta + 5, 2021) + randint(1, 10) + randint(1, 10), randint(1, 12), randint(1, 28))
    for _ in range(50)
]
fin = [
    (
        # randint(f[0] + 1, min(f[0] + 13, 2025)) if random() < pFinalizados else min(f[0] + randint(2, 15), randint(2023, 2035)),
        (y + randint(1, 6) + randint(0, 6)),
        randint(1, 12), randint(1, 28))
    for y, _, _ in fini
]
fbaja = [
    ((randint(y + 1, 2023), randint(1, 12), randint(1, 28)) if y < 2023 and random() < pBaja else None)
    for y, _, _ in fin
]

#### Agrupacion

In [1086]:
tabla_p = 'pr_proyectos'
campos_p = ('ID_PROYECTO', 'TX_DESCRIPCION', 'F_INICIO', 'F_FIN', 'F_BAJA', 'TX_LUGAR', 'TX_OBSERVACIONES')

data_p = [
    (
        i, descripciones[i], fdate(fini[i]), fdate(fin[i]), fdate(fbaja[i]),
        lugares[(randint(1, len(lugares)) + randint(1, len(lugares))) % len(lugares)], observaciones[i])
    for i in range(48)
]

#### Insercion

In [1087]:
insert(tabla_p, campos_p, data_p, True)

### Asignaciones

In [1088]:
ins = set()
while len(ins) < 100:

    e = None
    while e is None:
        e = data_e[randint(0, len(data_e) - 1)]
        if e[10] is not None:
            e = None
    
    p = None
    while p is None:
        p = data_p[randint(0, len(data_p) - 1)]
        if p[4] is not None:
            p = None

    if (p[0], e[0]) in ins:
        continue

    try:
        fecha = fdate((
            randint(max(int(e[9][:4]), int(p[2][:4])), 2023), randint(1, 12), randint(1, 28)
        ))
    except ValueError:
        continue

    res = insert('PR_EMPLEADOS_PROYECTO', ('ID_PROYECTO', 'ID_EMPLEADO', 'F_ALTA'), (p[0], e[0], fecha), False)
    if res is not None:
        print(res)
    else:
        ins.add((p[0], e[0]))

### Secuencias

In [1089]:
query('update `empleado-sequence` set next_val=%s', False, (data_e[-1][0] + 1,))
query('update `proyecto-sequence` set next_val=%s', False, (data_p[-1][0] + 1,))